# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3ca762b3152b87867a5cb81965393950029da58034d970291c1b7c4d94d5f003697f4cbb453baf753680a3b2c7140234ebd0c60b5495284c7202d86ac08b81d

test:
  secret_key_base: 6a831d1fe92e584d30eb29695eb5e4c03574fc9744015c18412c97d356e97510cd5086218924734727dc088659b1a68556803d84c4392945ac2dd0a7db2e2d81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
